# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blf.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1077, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.singleExpButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singleExpButton.sizePolicy().hasHeightForWidth())
        self.singleExpButton.setSizePolicy(sizePolicy)
        self.singleExpButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.singleExpButton.setFont(font)
        self.singleExpButton.setObjectName("singleExpButton")
        self.verticalLayout.addWidget(self.singleExpButton)
        self.dblExpButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dblExpButton.sizePolicy().hasHeightForWidth())
        self.dblExpButton.setSizePolicy(sizePolicy)
        self.dblExpButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dblExpButton.setFont(font)
        self.dblExpButton.setObjectName("dblExpButton")
        self.verticalLayout.addWidget(self.dblExpButton)
        self.polyButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polyButton.sizePolicy().hasHeightForWidth())
        self.polyButton.setSizePolicy(sizePolicy)
        self.polyButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.polyButton.setFont(font)
        self.polyButton.setObjectName("polyButton")
        self.verticalLayout.addWidget(self.polyButton)
        self.logButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logButton.sizePolicy().hasHeightForWidth())
        self.logButton.setSizePolicy(sizePolicy)
        self.logButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.logButton.setFont(font)
        self.logButton.setObjectName("logButton")
        self.verticalLayout.addWidget(self.logButton)
        self.hubertButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hubertButton.sizePolicy().hasHeightForWidth())
        self.hubertButton.setSizePolicy(sizePolicy)
        self.hubertButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hubertButton.setFont(font)
        self.hubertButton.setObjectName("hubertButton")
        self.verticalLayout.addWidget(self.hubertButton)
        self.sigButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sigButton.sizePolicy().hasHeightForWidth())
        self.sigButton.setSizePolicy(sizePolicy)
        self.sigButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sigButton.setFont(font)
        self.sigButton.setObjectName("sigButton")
        self.verticalLayout.addWidget(self.sigButton)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.mplwindow = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow.sizePolicy().hasHeightForWidth())
        self.mplwindow.setSizePolicy(sizePolicy)
        self.mplwindow.setMinimumSize(QtCore.QSize(600, 0))
        self.mplwindow.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.mplwindow.setObjectName("mplwindow")
        self.mplvl = QtWidgets.QVBoxLayout(self.mplwindow)
        self.mplvl.setObjectName("mplvl")
        self.gridLayout_4.addWidget(self.mplwindow, 0, 1, 1, 1)
        self.mplfigs_treeView = QtWidgets.QTreeView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplfigs_treeView.sizePolicy().hasHeightForWidth())
        self.mplfigs_treeView.setSizePolicy(sizePolicy)
        self.mplfigs_treeView.setMinimumSize(QtCore.QSize(200, 0))
        self.mplfigs_treeView.setMaximumSize(QtCore.QSize(300, 16777215))
        self.mplfigs_treeView.setObjectName("mplfigs_treeView")
        self.gridLayout_4.addWidget(self.mplfigs_treeView, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LB_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LB_lineEdit.sizePolicy().hasHeightForWidth())
        self.LB_lineEdit.setSizePolicy(sizePolicy)
        self.LB_lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.LB_lineEdit.setObjectName("LB_lineEdit")
        self.gridLayout_2.addWidget(self.LB_lineEdit, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.RB_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RB_lineEdit.sizePolicy().hasHeightForWidth())
        self.RB_lineEdit.setSizePolicy(sizePolicy)
        self.RB_lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.RB_lineEdit.setObjectName("RB_lineEdit")
        self.gridLayout_3.addWidget(self.RB_lineEdit, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.fileLoc_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileLoc_lineEdit.sizePolicy().hasHeightForWidth())
        self.fileLoc_lineEdit.setSizePolicy(sizePolicy)
        self.fileLoc_lineEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fileLoc_lineEdit.setObjectName("fileLoc_lineEdit")
        self.gridLayout.addWidget(self.fileLoc_lineEdit, 0, 1, 1, 1)
        self.fileChoose_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileChoose_pushButton.sizePolicy().hasHeightForWidth())
        self.fileChoose_pushButton.setSizePolicy(sizePolicy)
        self.fileChoose_pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fileChoose_pushButton.setFont(font)
        self.fileChoose_pushButton.setObjectName("fileChoose_pushButton")
        self.gridLayout.addWidget(self.fileChoose_pushButton, 0, 2, 1, 1)
        self.save_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_pushButton.sizePolicy().hasHeightForWidth())
        self.save_pushButton.setSizePolicy(sizePolicy)
        self.save_pushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.save_pushButton.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save_pushButton.setFont(font)
        self.save_pushButton.setObjectName("save_pushButton")
        self.gridLayout.addWidget(self.save_pushButton, 0, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1077, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.singleExpButton.setText(_translate("MainWindow", "Single Exponential"))
        self.dblExpButton.setText(_translate("MainWindow", "Double Exponential"))
        self.polyButton.setText(_translate("MainWindow", "Polynomial Degree n"))
        self.logButton.setText(_translate("MainWindow", "Logarithmic"))
        self.hubertButton.setText(_translate("MainWindow", "Hubert Curve"))
        self.sigButton.setText(_translate("MainWindow", "Sigmoidal"))
        self.groupBox.setTitle(_translate("MainWindow", "Left Bound"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Right Bound "))
        self.label.setText(_translate("MainWindow", "Choose Save File Location:"))
        self.fileChoose_pushButton.setText(_translate("MainWindow", "..."))
        self.save_pushButton.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

